spring:
  application:
    name: mediverse-backend
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /

mediverse:
  jwt:
    secret: ${MEDIVERSE_JWT_SECRET:${JWT_SECRET:YOUR_JWT_SECRET_KEY}}
    expiration-ms: 86400000 # 24 Hours
    refresh-expiration-ms: 604800000 # 7 Days
    issuer: mediverse-health-security

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
